### ISSUE TITLE
Add and re-implement tests to FairnessTestFactory

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#146]
## Tests to implement

- `min_gender_f1_score` @ArshaanNazir @alytarik 
- `max_gender_f1_score` @ArshaanNazir @alytarik 

## Config should look like this
```
fairness:
    min_gender_f1_score:
        min_score:
            male: 0.75
            female: 0.75
            unknown: 0.75

    max_gender_f1_score:
        max_score:
            male: 0.95
            female: 0.95
            unknown: 0.95
```

The user is able to assign 1 single threshold score to all gender categories in 2 ways:
1:
```
fairness:
    min_gender_f1_score:
        min_score: 0.75
```

2:
```
fairness:
    min_gender_f1_score

defaults:
    min_score: 0.75
```
NOTE: the min_score default option controls all metrics-based tests (fairness & accuracy)

## Results should look like this:

category | testype | original | testcase | expectedresult | actualresult | pass
-- | -- | -- | -- | -- | -- | --
fairness | min_gender_f1_score | - | male | 0.7 | 0.6 | FALSE
fairness | min_gender_f1_score | - | female | 0.7 | 0.8 | TRUE
fairness | min_gender_f1_score | - | unknown | 0.7 | 0.8 | TRUE

## Report should look like this (minimum pass rate will be 100% for all metrics-based tests from now on):

category | test_type | fail_count | pass_count | pass_rate | minimum_pass_rate | pass
-- | -- | -- | -- | -- | -- | --
fairness | min_gender_f1_score | 1 | 2 | 67% | 100% | FALSE

NOTE: @JulesBelveze is working on the underlying classifier
