### ISSUE TITLE
Shift accuracy from testrunner to AccuracyTestFactory

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#147]
Re-implement tests to follow new testfactory structure.

## Tests to cover:
- combinations of min_macro/micro/weighted_f1/precision/recall_score
- min_f1/precision/recall_score
- min_accuracy

## Config should look like this:

```
accuracy:
    min_f1_score:
        min_score:
            PER: 0.7
            ORG: 0.7
            LOC: 0.7

    min_recall_score:
        min_score:
            PER: 0.7
            ORG: 0.7
            LOC: 0.7

    min_micro_f1_score:
        min_score: 0.75
```

## Results should look like this:

category | testype | original | testcase | expectedresult | actualresult | pass
-- | -- | -- | -- | -- | -- | --
accuracy | min_macro_f1_score | - | macro | 0.7 | 0.75 | TRUE
accuracy | min_micro_f1_score | - | micro | 0.7 | 0.75 | TRUE
accuracy | min_weighted_f1_score | - | weighted | 0.7 | 0.75 | TRUE
accuracy | min_recall_score | - | PER | 0.7 | 0.6 | FALSE
accuracy | min_precision_score | - | PER | 0.7 | 0.9 | TRUE
accuracy | min_f1_score | - | PER | 0.7 | 0.75 | TRUE
accuracy | min_recall_score | - | ORG | 0.7 | 0.6 | FALSE
accuracy | min_precision_score | - | ORG | 0.7 | 0.9 | TRUE
accuracy | min_f1_score | - | ORG | 0.7 | 0.75 | TRUE

The user is able to assign 1 single threshold score to all labels in 2 ways:
1: 
```
fairness:
    min_recall_score:
        min_score: 0.75
```
NOTE: this will control the min_score for all labels

2:
```
fairness:
    min_recall_score

defaults:
    min_score: 0.75
```
NOTE: the min_score default option controls all metrics-based tests (fairness & accuracy)

ANOTHER NOTE: the macro/micro/accuracy scores that are not label-wise should always be at the top of the accuracy section of the dataframe

## Report should look like this (minimum pass rate will be 100% for all metrics-based tests from now on):

category | test_type | fail_count | pass_count | pass_rate | minimum_pass_rate | pass
-- | -- | -- | -- | -- | -- | --
accuracy | min_recall_score | 2 | 0 | 0% | 100% | FALSE
accuracy | min_precision_score | 0 | 2 | 100% | 100% | TRUE
accuracy | min_f1_score | 0 | 2 | 100% | 100% | TRUE
accuracy | min_macro_f1_score | 0 | 1 | 100% | 100% | TRUE
accuracy | min_micro_f1_score | 0 | 1 | 100% | 100% | TRUE
accuracy | min_weighted_f1_score | 0 | 1 | 100% | 100% | TRUE
