### ISSUE TITLE
Add support for LLM-related tasks & tests

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#312]
- https://github.com/JohnSnowLabs/nlptest/issues/350
- https://github.com/JohnSnowLabs/nlptest/issues/349
- https://github.com/JohnSnowLabs/nlptest/issues/353
- Refactoring how perturbations are applied to samples for QA vs other tasks
- https://github.com/JohnSnowLabs/nlptest/issues/357
- https://github.com/JohnSnowLabs/nlptest/issues/356
- https://github.com/JohnSnowLabs/nlptest/issues/355
- https://github.com/JohnSnowLabs/nlptest/issues/354

Config file:

```
model_parameters:
  user_prompt: "You are an intelligent bot and it is your responsibility to make sure to give a concise answer. \nAnswer:"
  temperature: 0.2
  max_tokens: 200

tests:
  defaults:
    min_pass_rate: 1.00

  robustness:
    lowercase:
      min_pass_rate: 0.70
    uppercase:
      min_pass_rate: 0.70

  bias:
    replace_to_female_pronoun:
      min_pass_rate: 0.70
```

API key:
 
os.env['OPENAI_API_KEY'] = 'xxx'
Harness(model='text-davinci', hub='openai', data='boolq-test')
