### ISSUE TITLE
`defaults` in config file should go under the `tests` section

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#354]
Previously we had this:
```
defaults:
    min_pass_rate: 1.00

tests:
  robustness:
    lowercase:
      min_pass_rate: 0.70
    uppercase:
      min_pass_rate: 0.70
```

We will now have this:
```
tests:
  defaults:
    min_pass_rate: 1.00

  robustness:
    lowercase:
      min_pass_rate: 0.70
    uppercase:
      min_pass_rate: 0.70
```
