### ISSUE TITLE
Model parameters should be regrouped in config file

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#356]
This is what they should look like:

```
model_parameters:
  user_prompt: "You are an intelligent bot and it is your responsibility to make sure to give a concise answer. \nAnswer:"
  temperature: 0.2
  max_tokens: 200

tests:
  ...
```
